### ISSUE TITLE
jhipster-alerter does not start

### ISSUE THREAD

**Issue by stas-sbi** [jhipster/jhipster-console#127]
jhipster-alerter does not start because elastalert prior to 0.2.x don't work anymore  (jhipster-console [uses](https://github.com/jhipster/jhipster-console/blob/96452fd/jhipster-alerter/Dockerfile#L7) 0.1.36). The reason is non-strict dependencies in [requirements.txt](https://github.com/Yelp/elastalert/blob/v0.1.36/requirements.txt#L16) leading to installation of stomp.py v5.x which does not work with python2.7

Either elastalert should be updated to version 0.2.x (better) or requirements.txt should patched be after [unpacking](https://github.com/jhipster/jhipster-console/blob/master/jhipster-alerter/Dockerfile#L7) (this ok as a temporary work around)

Logs:
```
Container timezone not modified
Elastalert index already exists in ES.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/elastalert/elastalert/elastalert.py", line 21, in <module>
    from alerts import DebugAlerter
  File "elastalert/alerts.py", line 23, in <module>
    import stomp
  File "/usr/local/lib/python2.7/site-packages/stomp.py-5.0.1-py2.7.egg/stomp/__init__.py", line 13, in <module>
    import stomp.connect as connect
  File "/usr/local/lib/python2.7/site-packages/stomp.py-5.0.1-py2.7.egg/stomp/connect.py", line 8, in <module>
    from stomp.protocol import *
  File "/usr/local/lib/python2.7/site-packages/stomp.py-5.0.1-py2.7.egg/stomp/protocol.py", line 6, in <module>
    from stomp.listener import *
  File "/usr/local/lib/python2.7/site-packages/stomp.py-5.0.1-py2.7.egg/stomp/listener.py", line 8, in <module>
    from time import monotonic
ImportError: cannot import name monotonic
```
